ADD MACRO LAB, ARG1, ARG2, ARG3
LAB:	ADD AX, ARG1
	ADD AX, ARG2
	ADD CX, ARG3
	ENDM
ADD2 MACRO LAB, ARG1, ARG2, ARG3
LAB:	MOV AX, ARG1
	ADD AX, ARG2
	ADD CX, ARG3
	ENDM
MAIN SEGMENT
	ASSUME CS:MAIN, DS:MAIN
	MOV AX, CS
	MOV DS, AX
;
	MOV AX, 1
	ADD LOOP1,DATA1,DATA2,DATA3
	ADD2 LOOP2,DATA1,DATA2,DATA3
	MOV AH, 4CH
	INT 21H
;
DATA1 DW 20
DATA2 DW 40
DATA3 DW 60
MAIN	ENDS
END